Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = false
  config.hostmanager.manage_guest = true
  
### Nginx VM ###
  config.vm.define "web01" do |web01|
    web01.vm.box = "bento/ubuntu-22.04"
    web01.vm.hostname = "web01"
	web01.vm.network "private_network", ip: "192.168.56.11"
        web01.vm.network "forwarded_port", guest: 80, host: 18089, auto_correct: true
  end
  
### tomcat vm ###
   config.vm.define "app01" do |app01|
    app01.vm.box = "bento/ubuntu-22.04"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.56.12"
	app01.vm.provider "vmware_desktop" do |v|
        v.vmx["memsize"] = "1024"
        v.vmx["numvcpus"] = "1"
         end
   end
   
### RabbitMQ vm  ####
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "bento/ubuntu-22.04"
	rmq01.vm.hostname = "rmq01"
    rmq01.vm.network "private_network", ip: "192.168.56.16"
  end
  
### Memcache vm  #### 
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "bento/ubuntu-22.04"
	mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", ip: "192.168.56.14"
  end
  
### DB vm  ####
  config.vm.define "db01" do |db01|
    db01.vm.box = "bento/ubuntu-22.04"
	db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.15"
  end
end
